spring.application.name=MCPEcom
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=vickyabishek
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework=INFO
spring.main.web-application-type=none
logging.file.name=mcp-server-MCPEcom.log
spring.ai.mcp.server.name=MCPEcom
spring.ai.mcp.server.version=1.0.0
spring.main.banner-mode=off
logging.pattern.console=

